name: ci

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: build
        run: ./mvnw clean install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: build
        uses: actions/checkout@v3

      - name: java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: tests
        run: ./mvnw test

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: jar
        run: ./mvnw package

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: deploy
        run: echo "Deploy realizado com sucesso"
